# Generated by Django 3.1.7 on 2023-10-10 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.patient')),
            ],
        ),
        migrations.RemoveField(
            model_name='drug',
            name='supplied_by',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
