# Generated by Django 3.1.7 on 2023-10-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20231010_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthhistory',
            name='diagnosis',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
