# Generated by Django 3.2.16 on 2023-11-14 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20231114_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.doctor'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.medicinesupply'),
        ),
    ]
