# Generated by Django 3.1.7 on 2023-10-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_dentalrecord_labrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labrecord',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='dentalrecord',
            field=models.FileField(null=True, upload_to='dentalrecord/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='labrecord',
            field=models.FileField(null=True, upload_to='labrecord/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='DentalRecord',
        ),
        migrations.DeleteModel(
            name='LabRecord',
        ),
    ]
