# Generated by Django 3.2.16 on 2023-11-14 04:39

from django.db import migrations


def update_prescribed_by_default(apps, schema_editor):
    Prescription = apps.get_model('data', 'Prescription')

    # Update existing records
    for prescription in Prescription.objects.filter(prescribed_by='No doctor available'):
        prescription.prescribed_by = None  # or set it to a valid Doctor instance
        prescription.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20231114_1233'),
    ]

    operations = [
        migrations.RunPython(update_prescribed_by_default),
    ]
