# Generated by Django 3.1.7 on 2023-10-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20231010_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='dentalrecord',
            new_name='dental_record',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='labrecord',
            new_name='laboratory_record',
        ),
    ]
