# Generated by Django 4.2.6 on 2023-10-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20231010_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dental_record',
            field=models.FileField(null=True, upload_to='dental_record/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='laboratory_record',
            field=models.FileField(null=True, upload_to='laboratory_record/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
