# Generated by Django 4.2.6 on 2023-10-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_remove_patient_dental_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='prescribed_by',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescribed_drug',
        ),
    ]
