# Generated by Django 3.2.16 on 2023-11-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_remove_prescription_prescribed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='drug_code',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='manufacturer',
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('Nurse', 'Nurse'), ('Clinical Officer', 'Clinical Officer'), ('Public Health Officer', 'Public Health Officer'), ('Cleaner', 'Cleaner'), ('Security', 'Security'), ('Driver', 'Driver'), ('Counselor', 'Counselor'), ('Nutritionist', 'Nutritionist'), ('Doctor', 'Doctor')], max_length=100),
        ),
    ]
