# Generated by Django 4.2.6 on 2023-11-23 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_alter_orderform_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderForm',
            new_name='Order',
        ),
    ]
