# Generated by Django 3.2.16 on 2023-11-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_rename_orderform_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status_update',
            field=models.CharField(choices=[('RHU', 'RHU'), ('Refered to MCH', 'Refered to MCH')], default='RHU', max_length=50),
        ),
    ]
